language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

before_install:
  - phpenv rehash
  - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - COMPOSER_ROOT_VERSION=dev-master composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --no-interaction --dev install

script: phpunit

notifications:
  irc: "irc.freenode.org#ppi"

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly
